import { Inter } from "next/font/google";
// import "./globals.css";
import "./app.css";
import "./cb.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "FY2027 CD Needs Statement",
  description: "Generated by CD Needs Statement Generator",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
